controller_list:
  - name: fake_Arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
  - name: fake_End_Effectuator_controller
    joints:
      - wrist_3_joint
initial:  # Define initial robot poses.
  - group: Arm
    pose: up