<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!--
  Author: Kelsey Hawkins
  Contributers: Jimmy Da Silva, Ajit Krisshna N L, Muhammad Asif Rana
-->

  <xacro:include filename="$(find ur10_description)/urdf/ur10.transmission.xacro" />
  <xacro:include filename="$(find ur10_description)/urdf/ur10.gazebo.xacro" />

  <!--xacro:property name="pi" value="3.14159265" /-->

  <!-- Inertia parameters -->
  <xacro:property name="base_mass" value="4.0" />  <!-- This mass might be incorrect -->
  <xacro:property name="shoulder_mass" value="7.778" />
  <xacro:property name="upper_arm_mass" value="12.93" />
  <xacro:property name="forearm_mass" value="3.87" />
  <xacro:property name="wrist_1_mass" value="1.96" />
  <xacro:property name="wrist_2_mass" value="1.96" />
  <xacro:property name="wrist_3_mass" value="0.202" />

  <!-- These parameters are borrowed from the urcontrol.conf file
       but are not verified for the correct permutation.
       The permutation was guessed by looking at the UR5 parameters.
       Serious use of these parameters needs further inspection. -->
  <xacro:property name="shoulder_cog" value="0.00008 0.00244 -0.037" />
  <xacro:property name="upper_arm_cog" value="0.00001 0.15061 0.38757" />
  <xacro:property name="forearm_cog" value="-0.00012 0.06112 0.1984" />
  <xacro:property name="wrist_1_cog" value="-0.00021 -0.00112 0.02269" />
  <xacro:property name="wrist_2_cog" value="-0.00021 0.00112 0.002269" />
  <xacro:property name="wrist_3_cog" value="0 -0.001156 -0.00149" />

  <!-- Kinematic model -->
  <!-- Properties from urcontrol.conf -->
  <xacro:property name="ur10_d1" value="0.1273" />
  <xacro:property name="ur10_a2" value="-0.612" />
  <xacro:property name="ur10_a3" value="-0.5723" />
  <xacro:property name="ur10_d4" value="0.163941" />
  <xacro:property name="ur10_d5" value="0.1157" />
  <xacro:property name="ur10_d6" value="0.0922" />

  <!-- Arbitrary offsets for shoulder/elbow joints -->
  <xacro:property name="shoulder_offset" value="0.220941" />  <!-- measured from model -->
  <xacro:property name="elbow_offset" value="-0.1719" /> <!-- measured from model -->

  <!-- link lengths used in model -->
  <xacro:property name="shoulder_height" value="${ur10_d1}" />
  <xacro:property name="upper_arm_length" value="${-ur10_a2}" />
  <xacro:property name="forearm_length" value="${-ur10_a3}" />
  <xacro:property name="wrist_1_length" value="${ur10_d4 - elbow_offset - shoulder_offset}" />
  <xacro:property name="wrist_2_length" value="${ur10_d5}" />
  <xacro:property name="wrist_3_length" value="${ur10_d6}" />

  <xacro:macro name="cylinder_inertial" params="radius length mass *origin">
    <inertial>
      <mass value="${mass}" />
      <xacro:insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" />
    </inertial>
  </xacro:macro>


  <xacro:macro name="ur10_robot" params="prefix joint_limited">

    <link name="${prefix}base_link" >
      <visual>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/visual/Base.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/collision/base.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.038" mass="${base_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}shoulder_pan_joint" type="revolute">
      <parent link="${prefix}base_link" />
      <child link = "${prefix}shoulder_link" />
      <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}shoulder_link">
      <visual>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/visual/Shoulder.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/collision/shoulder.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.178" mass="${shoulder_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}shoulder_lift_joint" type="revolute">
      <parent link="${prefix}shoulder_link" />
      <child link = "${prefix}upper_arm_link" />
      <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="330.0" velocity="2.16"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="330.0" velocity="2.16"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}upper_arm_link">
      <visual>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/visual/UpperArm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/collision/upper_arm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-ur10_a2}" mass="${upper_arm_mass}">
        <origin xyz="0.0 0.0 ${-ur10_a2/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}elbow_joint" type="revolute">
      <parent link="${prefix}upper_arm_link" />
      <child link = "${prefix}forearm_link" />
      <origin xyz="0.0 ${elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="150.0" velocity="3.15"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}forearm_link">
      <visual>
         <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/visual/Forearm.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/collision/forearm.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="${-ur10_a3}" mass="${forearm_mass}">
        <origin xyz="0.0 0.0 ${-ur10_a3/2.0}" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_1_joint" type="revolute">
      <parent link="${prefix}forearm_link" />
      <child link = "${prefix}wrist_1_link" />
      <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_1_link">
      <visual>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/visual/Wrist1.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/collision/wrist_1.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_1_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_2_joint" type="revolute">
      <parent link="${prefix}wrist_1_link" />
      <child link = "${prefix}wrist_2_link" />
      <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0 0 1" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_2_link">
      <visual>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/visual/Wrist2.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/collision/wrist_2.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_2_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}wrist_3_joint" type="revolute">
      <parent link="${prefix}wrist_2_link" />
      <child link = "${prefix}wrist_3_link" />
      <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
      <axis xyz="0 1 0" />
      <xacro:unless value="${joint_limited}">
        <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="54.0" velocity="3.2"/>
      </xacro:unless>
      <xacro:if value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="54.0" velocity="3.2"/>
      </xacro:if>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <link name="${prefix}wrist_3_link">
      <visual>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/visual/Wrist3.dae"/>
        </geometry>
        <material name="LightGrey">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://ur10_description/meshes/ur10/collision/wrist_3.stl"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertial radius="0.075" length="0.12" mass="${wrist_3_mass}">
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      </xacro:cylinder_inertial>
    </link>

    <joint name="${prefix}ee_fixed_joint" type="fixed">
      <parent link="${prefix}wrist_3_link" />
      <child link = "${prefix}ee_link" />
      <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>

    <link name="${prefix}ee_link">
      <collision>
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.01 0 0"/>
      </collision>
    </link>




    <link name="${prefix}down_camera_link">
		<!--<pose> 0 0 0 0 0 0 </pose> !-->
		<inertial>
		    <origin xyz="0.0 0.0 0.05" rpy="0 0 0"/>
		    <mass value="1"/>
		    <inertia
			ixx="1.0" ixy="0.0" ixz="0.0"
			iyy="1.0" iyz="0.0"
			izz="1.0"/>
	    	</inertial>
		<collision name="collisionBox">
		    	<origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
			<geometry>
			<box size="0.03 0.03 0.03"/>
			</geometry>		
		</collision>
		<visual name="visualBox">
		    	<origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
			<geometry>
			<box size="0.03 0.03 0.03"/>
			</geometry>		
		</visual>
		<!--   The circular lense if commented out due to the diffuculty of tuning/finding the right rpy configurations 
		<collision name="collisionLense">
			<origin xyz="0.0 0.0 -0.02" rpy="0 ${pi/2.0} 0"/>
			<geometry>
				<cylinder length="0.02" radius="0.02"/>
			</geometry>		
		</collision>
		<visual name="visualLense">
			<origin xyz="0.0 0.0 -0.02" rpy="0 ${pi/2.0} 0"/>
			<geometry>
				<cylinder length="0.02" radius="0.02"/>	
			</geometry>			
		</visual> !-->
	</link>
    <joint name="${prefix}down_camera_joint" type="fixed">
      <parent link="${prefix}wrist_2_link" />
      <child link = "${prefix}down_camera_link" />
      <origin xyz="-0.06 0.0 0.12" rpy="0.0 ${-pi/2.0} ${pi/2.0}" />
    </joint>
    <gazebo reference = "${prefix}down_camera_link">
		<sensor  type="camera" name="Down Camera Sensor">
			<update_rate>50</update_rate>
			<always_on>true</always_on>
			<visualize>true</visualize>
			<camera>
				<pose> 0.0 0.0 0.0 0.0 0.0 0.0</pose>
				<horizontal_fov>1.047</horizontal_fov>
				<image>
					<height>786</height>
					<width>786</width>
				</image>
				<!--<save enabled=True>
					<path>"~/CameraData"</path>
				</save>-->
				<noise>
				    <type>gaussian</type>
				    <mean>0.0</mean>
				    <stddev>0.01</stddev>
				</noise>
				<clip>
				    <near>0.1</near>
				    <far>100</far>
				</clip>
				<distortion>
				   <k1>-0.25</k1>
				   <k2>0.12</k2>
				   <k3>0.0</k3>
				   <p1>-0.00028</p1>
				   <p2>-0.00005</p2>
				   <center>0.5 0.5</center>
				</distortion>
			</camera>
		        <plugin name="down_camera_controller" filename="libgazebo_ros_camera.so">
		            <alwaysOn>true</alwaysOn>
		            <updateRate>0.0</updateRate>
		            <cameraName>Arm/down_camera</cameraName>
		            <imageTopicName>image_raw</imageTopicName>
		            <cameraInfoTopicName>camera_info</cameraInfoTopicName>
		            <frameName>${prefix}down_camera_link</frameName>
		            <hackBaseline>0.07</hackBaseline>
		            <distortionK1>0.0</distortionK1>
		            <distortionK2>0.0</distortionK2>
		            <distortionK3>0.0</distortionK3>
		            <distortionT1>0.0</distortionT1>
		            <distortionT2>0.0</distortionT2>
		        </plugin>
		</sensor>
	</gazebo>



	<link name="${prefix}right_camera_link">
		<!--<pose> 0 0 0 0 0 0 </pose> !-->
		<inertial>
		    <origin xyz="0.0 0.0 0.05" rpy="0 0 0"/>
		    <mass value="1"/>
		    <inertia
			ixx="1.0" ixy="0.0" ixz="0.0"
			iyy="1.0" iyz="0.0"
			izz="1.0"/>
	    	</inertial>
		<collision name="collisionBox">
		    	<origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
			<geometry>
			<box size="0.03 0.03 0.03"/>
			</geometry>		
		</collision>
		<visual name="visualBox">
		    	<origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
			<geometry>
			<box size="0.03 0.03 0.03"/>
			</geometry>		
		</visual>
		<!--   The circular lense if commented out due to the diffuculty of tuning/finding the right rpy configurations 
		<collision name="collisionLense">
			<origin xyz="0.0 0.0 -0.02" rpy="0 ${pi/2.0} 0"/>
			<geometry>
				<cylinder length="0.02" radius="0.02"/>
			</geometry>		
		</collision>
		<visual name="visualLense">
			<origin xyz="0.0 0.0 -0.02" rpy="0 ${pi/2.0} 0"/>
			<geometry>
				<cylinder length="0.02" radius="0.02"/>	
			</geometry>			
		</visual> !-->
	</link>
    <joint name="${prefix}right_camera_joint" type="fixed">
      <parent link="${prefix}wrist_2_link" />
      <child link = "${prefix}right_camera_link" />
      <origin xyz="-0.06 0.0 0.08" rpy="0.0 0.0 ${pi/2.0}" />
    </joint>
    <gazebo reference = "${prefix}right_camera_link">
		<sensor  type="camera" name="Right Camera Sensor">
			<update_rate>50</update_rate>
			<always_on>true</always_on>
			<visualize>true</visualize>
			<camera>
				<pose> 0.0 0.0 0.0 0.0 0.0 0.0</pose>
				<horizontal_fov>1.047</horizontal_fov>
				<image>
					<height>786</height>
					<width>786</width>
				</image>
				<!--<save enabled=True>
					<path>"~/CameraData"</path>
				</save>-->
				<noise>
				    <type>gaussian</type>
				    <mean>0.0</mean>
				    <stddev>0.01</stddev>
				</noise>
				<clip>
				    <near>0.1</near>
				    <far>100</far>
				</clip>
				<distortion>
				   <k1>-0.25</k1>
				   <k2>0.12</k2>
				   <k3>0.0</k3>
				   <p1>-0.00028</p1>
				   <p2>-0.00005</p2>
				   <center>0.5 0.5</center>
				</distortion>
			</camera>
		        <plugin name="right_camera_controller" filename="libgazebo_ros_camera.so">
		            <alwaysOn>true</alwaysOn>
		            <updateRate>0.0</updateRate>
		            <cameraName>Arm/right_camera</cameraName>
		            <imageTopicName>image_raw</imageTopicName>
		            <cameraInfoTopicName>camera_info</cameraInfoTopicName>
		            <frameName>${prefix}right_camera_link</frameName>
		            <hackBaseline>0.07</hackBaseline>
		            <distortionK1>0.0</distortionK1>
		            <distortionK2>0.0</distortionK2>
		            <distortionK3>0.0</distortionK3>
		            <distortionT1>0.0</distortionT1>
		            <distortionT2>0.0</distortionT2>
		        </plugin>
		</sensor>
	</gazebo>



    <xacro:ur10_arm_transmission prefix="${prefix}" />
    <xacro:ur10_arm_gazebo prefix="${prefix}" />

    <!-- ROS base_link to UR 'Base' Coordinates transform -->
    <link name="${prefix}base"/>
    <joint name="${prefix}base_link-base_fixed_joint" type="fixed">
    <!-- NOTE: this rotation is only needed as long as base_link itself is
    not corrected wrt the real robot (ie: rotated over 180
    degrees)
    -->
    <origin xyz="0 0 0" rpy="0 0 ${-pi}"/>
    <parent link="${prefix}base_link"/>
    <child link="${prefix}base"/>
    </joint>
    <!-- Frame coincident with all-zeros TCP on UR controller -->
    <link name="${prefix}tool0"/>
    <joint name="${prefix}wrist_3_link-tool0_fixed_joint" type="fixed">
    <origin xyz="0 ${wrist_3_length} 0" rpy="${pi/-2.0} 0 0"/>
    <parent link="${prefix}wrist_3_link"/>
    <child link="${prefix}tool0"/>
    </joint>

  </xacro:macro>
</robot>
